steps:
  - unicode_syntax:
      add_language_pragma: true

  - simple_align:
      cases: always
      top_level_patterns: always
      records: always
      multi_way_if: always

  - imports:
      align: global
      list_align: after_alias
      pad_module_names: true
      long_list_align: inline
      empty_list_align: inherit
      list_padding: 4
      separate_lists: true
      space_surround: false
      ghc_lib_parser: false

  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: true
      language_prefix: LANGUAGE

  - tabs:
      spaces: 8

  - trailing_whitespace: {}
  - squash: {}

columns: 80
newline: lf
cabal: true
