# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/home/dwd/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
packages: []
extra-deps:
- apply-refact-0.6.0.0
- hlint-2.2.3
- hoogle-5.0.17.11
- intero-0.1.40
- stylish-haskell-0.9.4.3
- QuickCheck-2.13.2
resolver: lts-14.12
recommend-stack-upgrade: true